#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_keybase="$(keybase --version 2>/dev/null | awk '{print $3}' | cut -d- -f1 || true)"
  jq -n --arg keybase "$ver_keybase" '{keybase: $keybase}'
}

version "$@"
